include $(GOROOT)/src/Make.$(GOARCH)

TARG=gelo/commands
GOFILES=\
	all.go\
	misc.go\
	argparse.go\
	names.go\
	control.go\
	types.go\
	port.go\
	string.go\
	dict.go\
	math.go\
	list.go\
	logic.go\
	copy.go\
	combinator.go\
	io.go\
	regexp.go\
	error.go\
	util.go

include $(GOROOT)/src/Make.pkg
