include $(GOROOT)/src/Make.$(GOARCH)

TARG=gelo
GOFILES=\
	parser.go\
	interpreter.go\
	vm.go\
	api.go\
	namespace.go\
	trace.go\
	types.go\
	port.go\
	list.go\
	dict.go\
	sym.go\
	bool.go\
	number.go\
	quote.go\
	error.go\
	builtins.go\
	util.go\
	listbuilder.go\
	unparser.go

include $(GOROOT)/src/Make.pkg
